version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: animedia.dev.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    # extra_hosts:
    # - "host.docker.internal:host-gateway"
